Enable nodding
discos/discos pull request #791
Opened 2022-12-21 10:07 UTC by giuseppe-carboni

@aorlati @carlomigoni @LorenzoMonti time to push this branch onto the master, do you have any test to suggest I perform onto this branch other than build everything from scratch and run a couple of schedules and tests again?

2022-12-21 10:11 UTC, carlomigoni approved these changes

2022-12-21 10:39 UTC, LorenzoMonti approved these changes

2022-12-21 15:21 UTC, aorlati requested changes
Please take note of this change in CHANGELOG in the root directory.

2023-01-10 09:58 UTC, aorlati approved these changes

2023-01-10 16:08 UTC, merged