Fix #853, allowed setSection=*,... to configure all sections
discos/discos pull request #854
Opened 2024-03-22 15:03 UTC by giuseppe-carboni

This fix is for TotalPower and Sardara backends

2024-03-22 16:39 UTC, aorlati requested changes
Please add the entry in the changelog. This is a meaningful modification and should be reported and ported id the user guide as well.

2024-03-22 17:18 UTC, giuseppe-carboni commented
@aorlati you are absolutely right, I always forget about the changelog. I will update it now.

2024-03-25 08:38 UTC, aorlati approved these changes

2024-03-29 07:50 UTC, sergiopoppi approved these changes

2024-04-02 08:32 UTC, merged